export {default as MainPage} from './MainPage';
export {default as ErrorPage} from './ErrorPage';
export {default as PeoplePage} from './PeoplePage';
export {default as PlanetPage} from './PlanetPage';
export {default as StarshipPage} from './StarshipPage';
export {default as MainPageContent} from './MainPageContent';
export {default as FullPersonPage} from './FullPersonPage';
export {default as FullPlanetPage} from './FullPlanetPage';
export {default as FullStarshipPage} from './FullStarshipPage';
